### PR TITLE
Provide lprofGetHostName for all windows environments

### PR DESCRIPTION
**Pull request by mati865**
Prerequisite for PGO on `windows-gnu` target.

cc @alexcrichton @michaelwoerister

### CODE REVIEW

**Comment by michaelwoerister** [comment]
Thanks, @mati865! 

I'm not sure what our policy regarding this fork of compiler-rt is...

**Comment by mati865** [comment]
I'm not sure either so I pinged Alex.

BTW with slight change to rust repository PGO seems to work and size of hello world example dropped from 2.4 MiB to 1.4 MiB.

**Comment by alexcrichton** [comment]
It's fine to patch up our forks of LLVM projects as we typically do it all the time. I've long wanted to unify this repository and the llvm-project repository, and especially if we're going to carry special patches here I think we'll instead want to use llvm-project. Can this be sent to the llvm-project repository instead?

**Comment by mati865** [comment]
No problem for me if you plan on switching `compiler-builtins` to use `llvm-project` soon.

**Comment by alexcrichton** [comment]
The switch has happened in https://github.com/rust-lang-nursery/compiler-builtins/pull/294

**Comment by mati865** [comment]
Oh, nice.

**Pull request closed without merging**
